CREATE TABLE "CLIENTES" 
("ID" VARCHAR2(20) NOT NULL ENABLE, 
	"APELLIDO" VARCHAR2(30) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(30) NOT NULL ENABLE, 
	"DOCUMENTO" VARCHAR2(8) NOT NULL ENABLE, 
	"CAJA_DE_AHORRO" VARCHAR2(20), 
	"CUENTA_CORRIENTE" VARCHAR2(20), 
	"USUARIO" VARCHAR2(12) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(12) NOT NULL ENABLE, 
	"ACTIVO" VARCHAR2(1) NOT NULL ENABLE, CONSTRAINT 
	"ID_CLIENTES_CON" PRIMARY KEY ("ID") ENABLE 
) 
	
/ CREATE TABLE "CUENTAS" 
("NUMERO" VARCHAR2(20) NOT NULL ENABLE, 
 "CLIENTE_ID" VARCHAR2(20) NOT NULL ENABLE, 
 "TIPO" VARCHAR2(2) NOT NULL ENABLE, 
 "SALDO" NUMBER(15,2) NOT NULL ENABLE, 
 "SOBREGIRO" NUMBER(15,2) NOT NULL ENABLE, 
 CONSTRAINT "CUENTAS_PK" PRIMARY KEY ("NUMERO") ENABLE, 
 CONSTRAINT "ID_TITULAR_CON" FOREIGN KEY ("CLIENTE_ID") REFERENCES "CLIENTES" ("ID") ENABLE ) 
/
